name: "Build and Deploy Documentation"
on: 
  push:
    branches:
     - "graph4nlp-documentation"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: build
      uses: actions/checkout@v2
    - name: build docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "pip install sphinx_rtd_theme && pip install torchtext && pip install numpydoc && pip install graph4nlp"
        build-command: "make html"
    - name: Deploy GH page
      uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        branch: "graph4nlp-documentation"
        FOLDER: docs/build/html
        TARGET_FOLDER: docs/
